[2023-07-04T21:15:23.695+0530] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stackexchange_elt.dbt_curation scheduled__2023-07-02T00:00:00+00:00 [queued]>
[2023-07-04T21:15:23.712+0530] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stackexchange_elt.dbt_curation scheduled__2023-07-02T00:00:00+00:00 [queued]>
[2023-07-04T21:15:23.712+0530] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2023-07-04T21:15:23.759+0530] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): dbt_curation> on 2023-07-02 00:00:00+00:00
[2023-07-04T21:15:23.762+0530] {standard_task_runner.py:57} INFO - Started process 12003 to run task
[2023-07-04T21:15:23.767+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'stackexchange_elt', 'dbt_curation', 'scheduled__2023-07-02T00:00:00+00:00', '--job-id', '49', '--raw', '--subdir', 'DAGS_FOLDER/load_data_dag.py', '--cfg-path', '/var/folders/1q/9_fjtq3x20g5lbhb24f74l380000gn/T/tmp6hra8lfu']
[2023-07-04T21:15:23.772+0530] {standard_task_runner.py:85} INFO - Job 49: Subtask dbt_curation
[2023-07-04T21:15:23.799+0530] {task_command.py:410} INFO - Running <TaskInstance: stackexchange_elt.dbt_curation scheduled__2023-07-02T00:00:00+00:00 [running]> on host shubhams-macbook-air.local
[2023-07-04T21:15:23.833+0530] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your-email@example.com' AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='stackexchange_elt' AIRFLOW_CTX_TASK_ID='dbt_curation' AIRFLOW_CTX_EXECUTION_DATE='2023-07-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-02T00:00:00+00:00'
[2023-07-04T21:15:23.835+0530] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/1q/9_fjtq3x20g5lbhb24f74l380000gn/T
[2023-07-04T21:15:23.836+0530] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'dbt run --models tag:curation --profiles-dir .']
[2023-07-04T21:15:23.843+0530] {subprocess.py:86} INFO - Output:
[2023-07-04T21:15:28.461+0530] {subprocess.py:93} INFO - [0m15:45:28  Running with dbt=1.5.2
[2023-07-04T21:15:28.465+0530] {subprocess.py:93} INFO - [0m15:45:28  Encountered an error:
[2023-07-04T21:15:28.466+0530] {subprocess.py:93} INFO - Runtime Error
[2023-07-04T21:15:28.466+0530] {subprocess.py:93} INFO -   No dbt_project.yml found at expected path /private/var/folders/1q/9_fjtq3x20g5lbhb24f74l380000gn/T/airflowtmpyuu1daii/dbt_project.yml
[2023-07-04T21:15:28.466+0530] {subprocess.py:93} INFO -   Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
[2023-07-04T21:15:28.466+0530] {subprocess.py:93} INFO - 
[2023-07-04T21:15:30.349+0530] {subprocess.py:97} INFO - Command exited with return code 2
[2023-07-04T21:15:30.359+0530] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/shubhampriyadarshi/.pyenv/versions/3.9.16/lib/python3.9/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-07-04T21:15:30.363+0530] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=stackexchange_elt, task_id=dbt_curation, execution_date=20230702T000000, start_date=20230704T154523, end_date=20230704T154530
[2023-07-04T21:15:30.368+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 49 for task dbt_curation (Bash command failed. The command returned a non-zero exit code 2.; 12003)
[2023-07-04T21:15:30.392+0530] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-04T21:15:30.406+0530] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
