[2023-07-04T21:15:32.889+0530] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stackexchange_elt.dbt_curation scheduled__2023-07-03T00:00:00+00:00 [queued]>
[2023-07-04T21:15:32.893+0530] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stackexchange_elt.dbt_curation scheduled__2023-07-03T00:00:00+00:00 [queued]>
[2023-07-04T21:15:32.893+0530] {taskinstance.py:1308} INFO - Starting attempt 2 of 2
[2023-07-04T21:15:32.902+0530] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): dbt_curation> on 2023-07-03 00:00:00+00:00
[2023-07-04T21:15:32.905+0530] {standard_task_runner.py:57} INFO - Started process 12047 to run task
[2023-07-04T21:15:32.911+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'stackexchange_elt', 'dbt_curation', 'scheduled__2023-07-03T00:00:00+00:00', '--job-id', '50', '--raw', '--subdir', 'DAGS_FOLDER/load_data_dag.py', '--cfg-path', '/var/folders/1q/9_fjtq3x20g5lbhb24f74l380000gn/T/tmpxddhrmzy']
[2023-07-04T21:15:32.913+0530] {standard_task_runner.py:85} INFO - Job 50: Subtask dbt_curation
[2023-07-04T21:15:32.956+0530] {task_command.py:410} INFO - Running <TaskInstance: stackexchange_elt.dbt_curation scheduled__2023-07-03T00:00:00+00:00 [running]> on host shubhams-macbook-air.local
[2023-07-04T21:15:32.990+0530] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='your-email@example.com' AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='stackexchange_elt' AIRFLOW_CTX_TASK_ID='dbt_curation' AIRFLOW_CTX_EXECUTION_DATE='2023-07-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-03T00:00:00+00:00'
[2023-07-04T21:15:32.992+0530] {subprocess.py:63} INFO - Tmp dir root location: /var/folders/1q/9_fjtq3x20g5lbhb24f74l380000gn/T
[2023-07-04T21:15:32.992+0530] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'dbt run --models tag:curation --profiles-dir .']
[2023-07-04T21:15:32.999+0530] {subprocess.py:86} INFO - Output:
[2023-07-04T21:15:35.213+0530] {subprocess.py:93} INFO - [0m15:45:35  Running with dbt=1.5.2
[2023-07-04T21:15:35.215+0530] {subprocess.py:93} INFO - [0m15:45:35  Encountered an error:
[2023-07-04T21:15:35.216+0530] {subprocess.py:93} INFO - Runtime Error
[2023-07-04T21:15:35.216+0530] {subprocess.py:93} INFO -   No dbt_project.yml found at expected path /private/var/folders/1q/9_fjtq3x20g5lbhb24f74l380000gn/T/airflowtmpsx0z2hne/dbt_project.yml
[2023-07-04T21:15:35.216+0530] {subprocess.py:93} INFO -   Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
[2023-07-04T21:15:35.217+0530] {subprocess.py:93} INFO - 
[2023-07-04T21:15:36.549+0530] {subprocess.py:97} INFO - Command exited with return code 2
[2023-07-04T21:15:36.558+0530] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/shubhampriyadarshi/.pyenv/versions/3.9.16/lib/python3.9/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-07-04T21:15:36.560+0530] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=stackexchange_elt, task_id=dbt_curation, execution_date=20230703T000000, start_date=20230704T154532, end_date=20230704T154536
[2023-07-04T21:15:36.566+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 50 for task dbt_curation (Bash command failed. The command returned a non-zero exit code 2.; 12047)
[2023-07-04T21:15:36.600+0530] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-04T21:15:36.614+0530] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
